---
rvm_install: false
nvm_install: false
docker_install: false
google_chrome_install: false
lazygit_install: false
aws_cli_install: false
terraform_install: false

apt_manage: false
apt_install_packages: []
apt_remove_packages: []

snap_install_packages: []
snap_install_classic_packages: []
snap_remove_packages: []
