---
- name: "Architecture is AMD64?"
  ansible.builtin.set_fact:
    repo_architecture: amd64
  when: ansible_architecture == "x86_64"

- name: Signing Key
  ansible.builtin.apt_key :
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ repo_architecture }}] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    filename: docker
  become: yes
